---
name: Check for DNM labels

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited
      - labeled
      - unlabeled

jobs:
  check-for-DNM:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if PR is DNM
        env:
          GITHUB_CONTEXT: ${{ toJson(github.event.pull_request.labels) }}
        run: |
           echo "$GITHUB_CONTEXT"
