---
name: Check for DNM labels

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited
      - labeled
      - unlabeled

jobs:
  check-for-DNM:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if PR is DNM
        env:
          LABEL_LIST: ${{ toJson(github.event.pull_request.labels.*.name) }}
        run: |
          printf '${{ env.PR_LABEL_LIST }}'
          echo "This PR has a DNM label."
          exit 1
