---
name: Check for DNM labels

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited
      - labeled
      - unlabeled

jobs:
  check-for-DNM:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if PR is DNM
        run: |
          echo "$(github.event.pull_request.labels.*.name)"
          exit 1
