---
name: Sync a target branch with source branch
on:
  repository_dispatch:
    types: [trigger-sync]

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          persist-credentials: true

      - name: Git config
        run: |
          git config --global user.name "openstack-k8s-ci-robot"
          git config --global user.email "openstack-k8s@redhat.com"

      - name: Rebase and Push
        run: |
          git fetch origin ${{ github.event.client_payload.source-branch || "main" }}
          git checkout ${{ github.event.client_payload.target-branch || "ananya-do-not-use-tmp" }}
          git rebase ${{ github.event.client_payload.source-branch || "main" }}
          git push origin ${{ github.event.client_payload.target-branch || "ananya-do-not-use-tmp" }}
