name: Sync branches with external trigger

on:
  workflow_dispatch:
    inputs:
      source-branch:
        required: false
        default: 'main'
      target-branch:
        required: false
        default: 'ananya-do-not-use-tmp'

jobs:
  trigger-sync:
    uses: frenzyfriday/frenzyfriday-testproject/.github/workflows/sync_branches_with_ext_trigger.yml@main
    with:
      source-branch: ${{ inputs.source-branch }}
      target-branch: ananya-do-not-use-tmp # Hardcoded till testing finishes
