---
name: Sync Olive branch with Main
on:
  workflow_call:
    inputs:
      source-branch:
        required: true
        type: string
      target-branch:
        required: true
        type: string

jobs:
  force-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Force Push Branch
        run: |
          git fetch origin ${{ inputs.source-branch }}
          git checkout ${{ inputs.target-branch }}
          git rebase ${{ inputs.source-branch }}
          git push origin ${{ inputs.target-branch }}