---
name: Bad person sync workflow
on:
  repository_dispatch:
    types: [trigger-sync]

jobs:
  bad-person-trigger-sync:
    uses: frenzyfriday/frenzyfriday-testproject/.github/workflows/sync_branches_reusable_workflow.yml@main
    with:
      source-branch: bad-person
      target-branch: ananya-do-not-use-tmp # Hardcoded till testing finishes
    secrets:
      ssh-key: ${{ secrets.DEPLOY_KEY }}
