---
name: Sync a target branch with source branch
on:
  repository_dispatch:
    types: [trigger-sync]

jobs:
  trigger-sync:
    uses: frenzyfriday/frenzyfriday-testproject/sync_branches_reusable_workflow.yml@main
    with:
      source-branch: ${{ inputs.source-branch }}
      target-branch: ananya-do-not-use-tmp # Hardcoded till testing finishes
      ssh-key: ${{ secrets.DEPLOY_KEY }}
